// A:/psaltiki/eyaggelia/testdata.js
 
   let datajson = 
 
 {
  "rows": [
    {
      "drawtype": "memo",
      "group": "enarxis",
      "stix": 0,
      "intable": 0,
      "book": "eyageli",
      "foldper": "enarxis",
      "foldkeim": "enarxis",
      "foldimg": "enarxis"
    },
    {
      "aa": 0,
      "group": "enarxis",
      "perigrafi": "Έναρξις.",
      "grklsper": "enarxis.",
      "keimeno": "ΕΝΑΡΞΙΣ",
      "grklskeim": "enarxis",
      "prosopo": "Ιερέας",
      "ermineia": "Η έναρξη της ακολουθίας.",
      "observations": "",
      "id": "enarxis",
      "type": "titlos",
      "peraudio": "1_p_enarxis.wav",
      "keimaudio": "1_k_enarxis.wav",
      "stix": 1,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "enarxis",
      "foldkeim": "enarxis",
      "foldimg": "enarxis"
    },
    {
      "aa": 1,
      "group": "enarxis",
      "perigrafi": "Ο παπάς να ευλογήσει την προσευχή που θα ακούσει ο κόσμος.",
      "grklsper": "o papas na evlogisei tin prosefxi pou tha akousei o kosmos.",
      "keimeno": "Εὐλόγησον, Δέσποτα.",
      "grklskeim": "evlogison, despota.",
      "prosopo": "Ψάλτης",
      "ermineia": "Ζητούμε την ευλογία του ιερέα.",
      "observations": "",
      "id": "evlogison_despota",
      "type": "dialog",
      "peraudio": "01-lk-1.wav",
      "keimaudio": "2_k_evlogison_despota.wav",
      "stix": 2,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "enarxis",
      "foldkeim": "enarxis",
      "foldimg": "enarxis"
    },
    {
      "aa": 2,
      "group": "enarxis",
      "perigrafi": "Ευλογημένη η βασιλεία του Πατρός, του Υιού και του Αγίου Πνεύματος.",
      "grklsper": "evlogimeni i vasileia tou patros tou yiou kai tou agiou pnevmatos.",
      "keimeno": "Εὐλογημένη ἡ βασιλεία τοῦ Πατρὸς καὶ τοῦ Υἱοῦ καὶ τοῦ Ἁγίου Πνεύματος, νῦν καὶ ἀεὶ καὶ εἰς τοὺς αἰῶνας τῶν αἰώνων.",
      "grklskeim": "evlogimeni i vasileia tou patros kai tou yiou kai tou agiou pnevmatos, nyn kai aei kai eis tous aionas ton aionon.",
      "prosopo": "Ιερέας",
      "ermineia": "Δοξάζουμε τη Βασιλεία του Θεού.",
      "observations": "",
      "id": "evlogimeni_i_vasileia",
      "type": "dialog",
      "peraudio": "01-lk-2.wav",
      "keimaudio": "3_k_evlogimeni_i_vasileia.wav",
      "stix": 3,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "enarxis",
      "foldkeim": "enarxis",
      "foldimg": "enarxis"
    },
    {
      "drawtype": "memo",
      "group": "peace_litany",
      "stix": 0,
      "intable": 0,
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 3,
      "group": "peace_litany",
      "perigrafi": "Ειρηνικά.",
      "grklsper": "eirinika.",
      "keimeno": "ΕΙΡΗΝΙΚΑ",
      "grklskeim": "eirinika",
      "prosopo": "Διάκονος",
      "ermineia": "Οι αρχικές δεήσεις.",
      "observations": "",
      "id": "eirinika",
      "type": "titlos",
      "peraudio": "1_p_eirinika.wav",
      "keimaudio": "1_k_eirinika.wav",
      "stix": 1,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 4,
      "group": "peace_litany",
      "perigrafi": "Για να παρακαλέσεις τον Κύριο, πρέπει να είσαι ήρεμος και να φωνάζεις: Κύριε ελέησον, Κύριε ελέησον, Κύριε ελέησον, Κύριε ελέησον.",
      "grklsper": "gia na parakaleseis ton kyrio prepei na eisai iremos kai na fonazeis kyrie eleison kyrie eleison kyrie eleison kyrie eleison.",
      "keimeno": "Ἐν εἰρήνῃ τοῦ Κυρίου δεηθῶμεν. Κύριε, ἐλέησον.",
      "grklskeim": "en eirini tou kyriou deithomen. kyrie, eleison.",
      "prosopo": "Διάκονος",
      "ermineia": "Με ειρήνη ας δεηθούμε.",
      "observations": "",
      "id": "en_eirini_tou_kyriou",
      "type": "dialog",
      "peraudio": "02-eir-1.wav",
      "keimaudio": "2_k_en_eirini_tou_kyriou.wav",
      "stix": 2,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 5,
      "group": "peace_litany",
      "perigrafi": "Για την ειρήνη που δίνει ο Θεός και τη σωτηρία των ψυχών, να παρακαλέσουμε τον Κύριο να μας δίνει δυνάμεις και φώτιση.",
      "grklsper": "gia tin eirini pou dinei o theos kai ti sotiria ton psychon na parakalesoume ton kyrio na mas dinei dynameis kai fotisi.",
      "keimeno": "Ὑπὲρ τῆς ἄνωθεν εἰρήνης καὶ τῆς σωτηρίας τῶν ψυχῶν ἡμῶν, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper tis anothen eirinis kai tis sotirias ton psychon imon, tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για την ουράνια ειρήνη.",
      "observations": "",
      "id": "yper_tis_anothen_eirinis",
      "type": "dialog",
      "peraudio": "02-eir-2.wav",
      "keimaudio": "3_k_yper_tis_anothen_eirinis.wav",
      "stix": 3,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 6,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουμε τον Κύριο, γιατί ο Κύριος είναι που κρατάει το σύμπαν και για την ειρήνη όλου του κόσμου και για τις εκκλησίες και να ενωθεί όλος ο κόσμος.",
      "grklsper": "na parakalesoume ton kyrio giati o kyrios einai pou krataei to sympan kai gia tin eirini olou tou kosmou kai gia tis ekklisies kai na enothei olos o kosmos.",
      "keimeno": "Ὑπὲρ τῆς εἰρήνης τοῦ σύμπαντος κόσμου, εὐσταθείας τῶν ἁγίων τοῦ Θεοῦ Ἐκκλησιῶν καὶ τῆς τῶν πάντων ἑνώσεως, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper tis eirinis tou sympantos kosmou efstatheias ton agion tou theou ekklision kai tis ton panton enoseos tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για την ειρήνη του κόσμου.",
      "observations": "",
      "id": "yper_tis_eirinis_tou_sympantos",
      "type": "dialog",
      "peraudio": "02-eir-3.wav",
      "keimaudio": "4_k_yper_tis_eirinis_tou_sympantos.wav",
      "stix": 4,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 7,
      "group": "peace_litany",
      "perigrafi": "Αυτοί οι άνθρωποι που είναι μες στην εκκλησία να παρακαλάνε το Θεό να τους βοηθήσει.",
      "grklsper": "autoi oi anthropoi pou einai mes stin ekklisia na parakalane to theo na tous voithisei.",
      "keimeno": "Ὑπὲρ τοῦ ἁγίου οἴκου τούτου καὶ τῶν μετὰ πίστεως, εὐλαβείας καὶ φόβου Θεοῦ εἰσιόντων ἐν αὐτῷ, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper tou agiou oikou toutou kai ton meta pisteos evlaveias kai fovou theou eisionton en auto tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για τον ιερό ναό.",
      "observations": "",
      "id": "yper_tou_agiou_oikou",
      "type": "dialog",
      "peraudio": "02-eir-4.wav",
      "keimaudio": "5_k_yper_tou_agiou_oikou.wav",
      "stix": 5,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 8,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουν τον Κύριο όλους τους Χριστιανούς που είναι μες στην εκκλησία και απέξω να δίνει δύναμη και φώτιση.",
      "grklsper": "na parakalesoun ton kyrio olous tous xristianous pou einai mes stin ekklisia kai apexo na dinei dynami kai fotisi.",
      "keimeno": "Ὑπὲρ τῶν εὐσεβῶν καὶ ὀρθοδόξων χριστιανῶν, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper ton evsevon kai orthodoxon xristianon tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για τους πιστούς.",
      "observations": "",
      "id": "yper_ton_evsevon",
      "type": "dialog",
      "peraudio": "02-eir-5.wav",
      "keimaudio": "6_k_yper_ton_evsevon.wav",
      "stix": 6,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 9,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουν τον Κύριο να δίνει δύναμη και φώτιση όλοι όσοι βρίσκονται στην εκκλησία και απέξω: τον Αρχιεπίσκοπο, τους παπάδες, το λαό, όλες τις ψυχές.",
      "grklsper": "na parakalesoun ton kyrio na dinei dynami kai fotisi oloi osoi vriskontai stin ekklisia kai apexo ton arxiepiskopo tous papades to lao oles tis psyxes.",
      "keimeno": "Ὑπὲρ τοῦ Ἀρχιεπισκόπου ἡμῶν (δεῖνος), τοῦ τιμίου πρεσβυτερίου, τῆς ἐν Χριστῷ διακονίας, παντὸς τοῦ κλήρου καὶ τοῦ λαοῦ, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper tou arxiepiskopou imon tou timiou presvysteriou tis en xristou diakonias pantos tou klirou kai tou laou tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για τον κλήρο και τον λαό.",
      "observations": "",
      "id": "yper_tou_arxiepiskopou",
      "type": "dialog",
      "peraudio": "02-eir-6.wav",
      "keimaudio": "7_k_yper_tou_arxiepiskopou.wav",
      "stix": 7,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 10,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουν τον Κύριο όλους τους πιστούς και όλα τα χωριά, όλες τις γειτονιές, να τους έχει καλά και να τους δίνει πάντα δύναμη.",
      "grklsper": "na parakalesoun ton kyrio olous tous pistous kai ola ta xoria oles tis geitonies na tous exei kala kai na tous dinei panta dynami.",
      "keimeno": "Ὑπὲρ τῆς πόλεως ταύτης, πάσης πόλεως καὶ χώρας καὶ τῶν πίστει οἰκούντων ἐν αὐταῖς, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper tis poleos tautis pasis poleos kai xoras kai ton pistei oikounton en autais tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για την πόλη και τη χώρα.",
      "observations": "",
      "id": "yper_tis_poleos_tautis",
      "type": "dialog",
      "peraudio": "02-eir-7.wav",
      "keimaudio": "8_k_yper_tis_poleos_tautis.wav",
      "stix": 8,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 11,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουμε τον Κύριο να καρποφορεί η γη, να κάνει καλό καιρό και όλοι να στεκόμαστε και να ζητάμε βοήθεια από τον Θεό.",
      "grklsper": "na parakalesoume ton kyrio na karpoforei i gi na kanei kalo kairo kai oloi na stekomaste kai na zhitame voitheia apo ton theo.",
      "keimeno": "Ὑπὲρ εὐκρασίας ἀέρων, εὐφορίας τῶν καρπῶν τῆς γῆς καὶ καιρῶν εἰρηνικῶν, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper evkrasias aeron evforias ton karpon tis gis kai kairon eirinikon tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για καλή σοδειά και καιρό.",
      "observations": "",
      "id": "yper_evkrasias_aeron",
      "type": "dialog",
      "peraudio": "02-eir-8.wav",
      "keimaudio": "9_k_yper_evkrasias_aeron.wav",
      "stix": 9,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 12,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλάμε τον Κύριο για αυτούς που ταξιδεύουν, που είναι άρρωστοι στα νοσοκομεία, τους ανήμπορους, τους ηλικιωμένους που δεν έχουν τη δύναμη. Ε ναι να το πω και αυτό ότι σκέφτηκε κανένας το φανταράκι, πόσο προσφέρει και πώς στέκεται προσοχή. Ποιος στέκεται προσοχή όπως στέκεται ο φαντάρος;",
      "grklsper": "na parakalame ton kyrio gia autous pou taxideuoun pou einai arrostoi sta nosokomeia tous animporous tous ilikiomenous pou den exoun ti dynami e nai na to po kai auto oti skeftike kanevas to fantaraki poso prosferei kai pos steketai prosoxi poios steketai prosoxi opos steketai o fantaros.",
      "keimeno": "Ὑπὲρ πλεόντων, ὁδοιπορούντων, νοσούντων, καμνόντων, αἰχμαλώτων καὶ τῆς σωτηρίας αὐτῶν, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper pleonton odoiporounton nosounton kamnonton aixmaloton kai tis sotirias auton tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για τους ταξιδιώτες και ασθενείς.",
      "observations": "",
      "id": "yper_pleonton_odoiporounton",
      "type": "dialog",
      "peraudio": "02-eir-9.wav",
      "keimaudio": "10_k_yper_pleonton_odoiporounton.wav",
      "stix": 10,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 13,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουμε τον Κύριο να μας προστατεύει από κάθε οργή, θλίψη και ανάγκη.",
      "grklsper": "na parakalesoume ton kyrio na mas prostateuei apo kathe orgi thlipsi kai anagki.",
      "keimeno": "Ὑπὲρ τοῦ ῥυσθῆναι ἡμᾶς ἀπὸ πάσης θλίψεως, ὀργῆς, κινδύνου καὶ ἀνάγκης, τοῦ Κυρίου δεηθῶμεν.",
      "grklskeim": "yper tou rysthenai imas apo pasis thlipseos orgis kindynou kai anagkis tou kyriou deithomen.",
      "prosopo": "Διάκονος",
      "ermineia": "Για προστασία από κινδύνους.",
      "observations": "",
      "id": "yper_tou_rysthenai",
      "type": "dialog",
      "peraudio": "02-eir-10.wav",
      "keimaudio": "11_k_yper_tou_rysthenai.wav",
      "stix": 11,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 14,
      "group": "peace_litany",
      "perigrafi": "Θεέ μου, ελέησέ μας, βοήθησέ μας και σώσε μας. Διαφύλαξέ μας σε όλα με τη θεία χάρη σου.",
      "grklsper": "thee mou eleise mas voithise mas kai sose mas diafylaxe mas se ola me ti theia xari sou.",
      "keimeno": "Ἀντιλαβοῦ, σῶσον, ἐλέησον καὶ διαφύλαξον ἡμᾶς, ὁ Θεός, τῇ σῇ χάριτι.",
      "grklskeim": "antilavou soson eleison kai diafylaxon imas o theos ti si xariti.",
      "prosopo": "Διάκονος",
      "ermineia": "Βοήθησε και σώσε μας Θεέ.",
      "observations": "",
      "id": "antilavou_soson_eleison",
      "type": "dialog",
      "peraudio": "02-eir-11.wav",
      "keimaudio": "12_k_antilavou_soson_eleison.wav",
      "stix": 12,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 15,
      "group": "peace_litany",
      "perigrafi": "Να δώσουμε όλη μας τη ζωή στον Χριστό και σε όλους τους Αγίους και στην Παναγία. Όλοι οι άνθρωποι πρέπει να αφήνουν τη δύναμή τους στον Χριστό, γιατί ο Χριστός είναι που κινεί το σύμπαν. Να αφήσουμε όλη μας τη ζωή και τη δύναμη που έχουμε στον Χριστό, τον Κύριο, τον Θεό μας.",
      "grklsper": "na dosoume oli mas ti zoi ston xristo kai se olous tous agious kai stin panagia oloi oi anthropoi prepei na afinoun ti dynami tous ston xristo giati o xristos einai pou kinei to sympan na afisoume oli mas ti zoi kai ti dynami pou exouμε ston xristo ton kyrio ton theo mas.",
      "keimeno": "Τῆς Παναγίας, ἀχράντου, ὑπερευλογημένης, ἐνδόξου, Δεσποίνης ἡμῶν Θεοτόκου καὶ ἀειπαρθένου Μαρίας, μετὰ πάντων τῶν Ἁγίων μνημονεύσαντες, ἑαυτοὺς καὶ ἀλλήλους καὶ πᾶσαν τὴν ζωὴν ἡμῶν, Χριστῷ τῷ Θεῷ παραθώμεθα.",
      "grklskeim": "tis panagias axrantou yperevlogimenis endoxou despoinis imon theotokou kai aeiparthenou marias meta panton ton agion mnimoneusantes eautous kai allilous kai pasan tin zoin imon xristo to theo parathometha.",
      "prosopo": "Διάκονος",
      "ermineia": "Ας αφιερωθούμε στον Χριστό.",
      "observations": "",
      "id": "tis_panagias_axrantou",
      "type": "dialog",
      "peraudio": "02-eir-12c.wav",
      "keimaudio": "13_k_tis_panagias_axrantou.wav",
      "stix": 13,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
  
    {
      "aa": 16,
      "group": "peace_litany",
      "perigrafi": "Να παρακαλέσουμε την Παναγίτσα μας και όλους τους Αγίους να μας δίνουν φώτιση και δύναμη και να αφήσουμε τη ζωή μας στον Κύριο Ιησού Χριστό. Ναι, και τα έργα μας· χωρίς έργα πού πας;",
      "grklsper": "na parakalesoume tin panagitsa mas kai olous tous agious na mas dinoun fotisi kai dynami kai na afisoume ti zoi mas ston kyrio iisou xristo. nai, kai ta erga mas; xoris erga pou pas;",
      "keimeno": "Τῆς Παναγίας, ἀχράντου, ὑπερευλογημένης, ἐνδόξου, Δεσποίνης ἡμῶν Θεοτόκου καὶ ἀειπαρθένου Μαρίας, μετὰ πάντων τῶν Ἁγίων μνημονεύσαντες, ἑαυτοὺς καὶ ἀλλήλους καὶ πᾶσαν τὴν ζωὴν ἡμῶν, Χριστῷ τῷ Θεῷ παραθώμεθα.",
      "grklskeim": "tis panagias axrantou yperevlogimenis endoxou despoinis imon theotokou kai aeiparthenou marias meta panton ton agion mnimoneusantes eautous kai allilous kai pasan tin zoin imon xristo to theo parathometha.",
      "prosopo": "Διάκονος",
      "ermineia": "Ας αφιερώσουμε τη ζωή μας στον Χριστό μέσω της Παναγίας.",
      "observations": "",
      "id": "tis_panagias_mnimoneusantes",
      "type": "dialog",
      "peraudio": "02-eir-12c2.wav",
      "keimaudio": "16_k_tis_panagias_mnimoneusantes.wav",
      "stix": 14,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
    {
      "aa": 17,
      "group": "peace_litany",
      "perigrafi": "Να αφήσουμε όλη μας τη ζωή και τη δύναμη που έχουμε στον Χριστό, τον Κύριο, τον Θεό μας.",
      "grklsper": "na afisoume oli mas ti zoi kai ti dynami pou exoume ston xristo ton kyrio to theo mas.",
      "keimeno": "Σοί, Κύριε.",
      "grklskeim": "soi, kyrie.",
      "prosopo": "Λαός",
      "ermineia": "Σε Εσένα, Κύριε.",
      "observations": "",
      "id": "soi_kyrie",
      "type": "dialog",
      "peraudio": "02-eir-12d.wav",
      "keimaudio": "17_k_soi_kyrie.wav",
      "stix": 15,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "eirinika",
      "foldkeim": "eirinika",
      "foldimg": "eirinika"
    },
   
   
    {
      "drawtype": "memo",
      "group": "antifona_a",
      "stix": 0,
      "aa": 17,
      "book": "eyageli",
      "foldper": "antifona_a",
      "foldkeim": "antifona_a",
      "foldimg": "antifona_a",
      "intable": 0
    },
    {
      "aa": 18,
      "group": "antifona_a",
      "perigrafi": "Τα Αντίφωνα Α: Α' Ευχή.",
      "grklsper": "ta antifona a: a efxi.",
      "keimeno": "Α' ΕΥΧΗ",
      "grklskeim": "A EFXI",
      "prosopo": "Ιερέας",
      "ermineia": "Η πρώτη ευχή της ακολουθίας των Αντιφώνων.",
      "observations": "",
      "id": "antifona_a_efxi",
      "type": "titlos",
      "peraudio": "18_p_antifona_a_efxi.wav",
      "keimaudio": "18_k_antifona_a_efxi.wav",
      "stix": 1,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "antifona_a",
      "foldkeim": "antifona_a",
      "foldimg": "antifona_a"
    },
    {
      "aa": 19,
      "group": "antifona_a",
      "perigrafi": "Κύριε ο Θεός μας, και τη δύναμή Σου δεν υπάρχει τρόπος να τη φανταστούμε και τη δόξα Σου δεν μπορούμε να την καταλάβουμε. Η αγάπη Σου είναι αμέτρητη και η φιλανθρωπία Σου ανέκφραστη, ελέησέ μας. Εσύ Δέσποτα, ρίξε το βλέμμα Σου πάνω μας και σε τούτο τον ναό, και δείξε σε μας και σε αυτούς που προσεύχονται μαζί μας πλούσια την αγάπη Σου και τη συμπόνια Σου. Γιατί σε Σένα πρέπει κάθε δόξα, τιμή και προσκύνηση, του Πατέρα, του Υιού και του Αγίου Πνεύματος, τώρα και πάντα και σε όλους τους αιώνες. Αμήν.",
      "grklsper": "kyrie o theos mas kai ti dynami sou den yparxei tropos na ti fantastoume kai ti doxa sou den mporoume na tin katalavoume. i agapi sou einai ametriti kai i filanthropia sou anekfrasti eleise mas. esy despota rixe to vlemma sou pano mas kai se touto ton nao kai deixte se mas kai se autous pou prosevxontai mazi mas plousia tin agapi sou kai ti symponia sou. giati se sena prepei kathe doxa timi kai proskynisi tou patera tou yiou kai tou agiou pnevmatos tora kai panta kai se olous tous aionas. amin.",
      "keimeno": "Κύριε ὁ Θεὸς ἡμῶν, οὗ τὸ κράτος ἀνείκαστον καὶ ἡ δόξα ἀκατάληπτος· οὗ τὸ ἔλεος ἀμέτρητον καὶ ἡ φιλανθρωπία ἄφατος· Αὐτὸς Δέσποτα, κατὰ τὴν εὐσπλαγχνίαν σου, ἐπίβλεψον ἐφ’ ἡμᾶς καὶ ἐπὶ τὸν ἅγιον οἶκον τοῦτον και ποίησον μεθ’ ἡμῶν, και τῶν συνευχομένων ἡμῖν, πλούσια τὰ ἐλέη σου και τοὺς οἰκτιρμούς σου. Ὅτι πρέπει σοι πᾶσα δόξα, τιμὴ καὶ προσκύνησις, τῷ Πατρὶ καὶ τῷ Υἱῷ καὶ τῷ Ἁγίῳ Πνεύματι, νῦν καὶ ἀεὶ καὶ εἰς τοὺς αἰῶνας τῶν αἰώνων. Ἀμήν.",
      "grklskeim": "kyrie o theos imon ou to kratos aneikaston kai i doxa akataliptos ou to eleos ametriton kai i filanthropia afatos autos despota kata tin evsplagxnian sou epivlepson ef imas kai epi ton agion oikon touton kai poiison meth imon kai ton synevxomenon imin plousia ta elei sou kai tous oiktirmous sou. oti prepei soi pasa doxa timi kai proskynisis to patri kai to yiou kai to agio pnevmati nyn kai aei kai eis tous aionas ton aionon. amin.",
      "prosopo": "Ιερέας",
      "ermineia": "Κύριε ο Θεός μας, του οποίου η δύναμη είναι ασύγκριτη και η δόξα ακατανόητη, του οποίου το έλεος είναι αμέτρητο και η αγάπη για τον άνθρωπο ανέκφραστη· Εσύ Δέσποτα, σύμφωνα με την ευσπλαχνία Σου, επίβλεψε εμάς και αυτόν τον άγιο ναό και χάρισε σε εμάς και σε όσους συμπροσεύχονται μαζί μας πλούσιο το έλεός Σου και τους οικτιρμούς Σου. Διότι Σου ανήκει κάθε δόξα, τιμή και προσκύνηση...",
      "observations": "",
      "id": "kyrie_o_theos_imon_efxi_a",
      "type": "dialog",
      "peraudio": "04-ea-1.wav",
      "keimaudio": "19_k_kyrie_o_theos_imon_efxi_a.wav",
      "stix": 2,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "antifona_a",
      "foldkeim": "antifona_a",
      "foldimg": "antifona_a"
    },
    {
      "aa": 20,
      "group": "antifona_a",
      "perigrafi": "Να ευλογεί η ψυχή μου τον Κύριο κι όλο το είναι μου να δοξάζει το όνομά Του. Με τις πρεσβείες της Θεοτόκου, σώσε Χριστέ εμάς. Δόξασε ψυχή μου τον Κύριο και μην ξεχνάς όλα τα καλά που σου έχει κάνει. Με τις πρεσβείες της Παναγίας να μας σώσει ο Χριστός. Ο Κύριος έχει το θρόνο Του στον ουρανό και η εξουσία Του είναι σε όλο τον κόσμο. Με τις πρεσβείες της Θεοτόκου, σώσε και εμάς. Δόξα στον Πατέρα, στον Υιό και στο Άγιο Πνεύμα και τώρα και πάντα και σε όλους τους αιώνες. Αμήν.",
      "grklsper": "na evlogei i psyxi mou ton kyrio ki olo to eine mou na doxazei to onoma tou. me tis presveies tis theotokou sose xriste emas. doxase psyxi mou ton kyrio kai min xexnas ola ta kala pou sou exei kanei. me tis presveies tis panagias na mas sosei o xristos. o kyrios exei to throno tou ston ourano kai i exousia tou einai se olo ton kosmo. me tis presveies tis theotokou sose kai emas. doxa ston patera ston yio kai sto agio pnevmato kai tora kai panta kai se olous tous aionas. amin.",
      "keimeno": "Εὐλόγει, ἡ ψυχή μου, τὸν Κύριον, καὶ πάντα τὰ ἐντός μου τὸ ὄνομα τὸ ἅγιον αὐτοῦ. Εὐλόγει, ἡ ψυχή μου, τὸν Κύριον, καὶ μὴ ἐπιλανθάνου πάσας τὰς ἀνταποδόσεις αὐτοῦ. Κύριος ἐν τῷ οὐρανῷ ἡτοίμασε τὸν θρόνον αὐτοῦ, καὶ ἡ βασιλεία αὐτοῦ πάντων δεσπόζει. Ταῖς πρεσβείαις τῆς Θεοτόκου, Σῶτερ, σῶσον ἡμᾶς. Δόξα Πατρὶ καὶ Υἱῷ καὶ Ἁγίῳ Πνεύματι, καὶ νῦν καὶ ἀεὶ καὶ εἰς τοὺς αἰῶνας τῶν αἰώνων. Ἀμήν.",
      "grklskeim": "evlogei i psyxi mou ton kyrion kai panta ta entos mou to onoma to agion autou. evlogei i psyxi mou ton kyrion kai mi epilanthanou pasas tas antapodoseis autou. kyrios en to ourano itoimase ton thronon autou kai i vasileia autou panton despozei. tais presveiais tis theotokou soter soson imas. doxa patri kai yiou kai agio pnevmati kai nyn kai aei kai eis tous aionas ton aionon. amin.",
      "prosopo": "Λαός",
      "ermineia": "Ευλόγησε, ψυχή μου, τον Κύριο και όλα τα εσωτερικά μου το άγιο όνομά Του. Ευλόγησε, ψυχή μου, τον Κύριο και μην ξεχνάς όλες τις ευεργεσίες Του. Ο Κύριος στον ουρανό ετοίμασε τον θρόνο Του και η βασιλεία Του εξουσιάζει τα πάντα. Με τις μεσιτείες της Θεοτόκου, Σωτήρα, σώσε μας.",
      "observations": "",
      "id": "evlogei_i_psyxi_mou_antifono_a",
      "type": "dialog",
      "peraudio": "04-ea-2.wav",
      "keimaudio": "20_k_evlogei_i_psyxi_mou_antifono_a.wav",
      "stix": 3,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "antifona_a",
      "foldkeim": "antifona_a",
      "foldimg": "antifona_a"
    },
    {
      "aa": 21,
      "group": "antifona_a",
      "perigrafi": "Να παρακαλέσουμε τον Κύριο με ηρεμία: Κύριε ελέησον, Κύριε ελέησον, Κύριε ελέησον. Βοήθησέ μας και σώσε μας Χριστούλη μου, ελέησέ μας και σε όλα διαφύλαξέ μας, Θεέ μου, με τη χάρη Σου. Να παρακαλέσουμε την Παναγία μας την ένδοξη Κυρία μας Θεοτόκο και αειπάρθενο Μαρία μαζί με όλους τους Αγίους και τους Αγγέλους και να αφήσουμε τη ζωή μας όλος ο κόσμος, όλοι μας, στον Θεό μας τον Ιησού Χριστό· σε Σένα Κύριε.",
      "grklsper": "na parakalesoume ton kyrio me iremia kyrie eleison kyrie eleison kyrie eleison. voithise mas kai sose mas xristouli mou eleise mas kai se ola diafylaxe mas thee mou me ti xari sou. na parakalesoume tin panagia mas tin endoxi kyria mas theotoko kai aeipartheno maria mazi me olous tous agious kai tous aggelous kai na afisoume ti zoi mas olos o kosmos oloi mas ston theo mas ton iisou xristo se sena kyrie.",
      "keimeno": "Ἔτι καὶ ἔτι ἐν εἰρήνῃ τοῦ Κυρίου δεηθῶμεν. Ἀντιλαβοῦ, σῶσον, ἐλέησον καὶ διαφύλαξον ἡμᾶς, ὁ Θεός, τῇ σῇ χάριτι. Τῆς Παναγίας, ἀχράντου, ὑπερευλογημένης, ἐνδόξου, Δεσποίνης ἡμῶν Θεοτόκου καὶ ἀειπαρθένου Μαρίας, μετὰ πάντων τῶν Ἁγίων μνημονεύσαντες, ἑαυτοὺς καὶ ἀλλήλους καὶ πᾶσαν τὴν ζωὴν ἡμῶν, Χριστῷ τῷ Θεῷ παραθώμεθα. Σοί, Κύριε.",
      "grklskeim": "eti kai eti en eirini tou kyriou deithomen. antilavou soson eleison kai diafylaxon imas o theos ti si xariti. tis panagias axrantou yperevlogimenis endoxou despoinis imon theotokou kai aeiparthenou marias meta panton ton agion mnimoneusantes eautous kai allilous kai pasan tin zoin imon xristo to theo parathometha. soi kyrie.",
      "prosopo": "Διάκονος",
      "ermineia": "Πάλι και πάλι με ειρήνη ας παρακαλέσουμε τον Κύριο. Βοήθησε, σώσε, ελέησε και διαφύλαξέ μας, Θεέ, με τη χάρη Σου. Την Παναγία, άχραντη, υπερευλογημένη... αφού μνημονεύσουμε, ας αφιερώσουμε τους εαυτούς μας και ο ένας τον άλλο και όλη τη ζωή μας στον Χριστό τον Θεό μας.",
      "observations": "",
      "id": "eti_kai_eti_antifono_a",
      "type": "dialog",
      "peraudio": "04-ea-3.wav",
      "keimaudio": "21_k_eti_kai_eti_antifono_a.wav",
      "stix": 4,
      "intable": 1,
      "drawtype": "rec",
      "keimscan": "x113",
      "book": "eyageli",
      "foldper": "antifona_a",
      "foldkeim": "antifona_a",
      "foldimg": "antifona_a"
    }
  ]
}
  

// Εξαγωγή για το Node.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = datajson;
}